# Generated by Django 4.1.5 on 2023-02-04 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 15, 0, 27, 909670, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='contact',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 15, 0, 27, 906670, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='item',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 15, 0, 27, 913669, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='lendingbook',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 15, 0, 27, 911669, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='lendingitem',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 15, 0, 27, 915669, tzinfo=datetime.timezone.utc)),
        ),
    ]
