# Generated by Django 4.1.5 on 2023-02-11 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_book_edited_at_alter_contact_edited_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 22, 35, 40, 716773, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 22, 35, 40, 716045, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 22, 35, 40, 718261, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lendingbook',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 22, 35, 40, 717439, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lendingitem',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 22, 35, 40, 718906, tzinfo=datetime.timezone.utc)),
        ),
    ]
