# Generated by Django 4.1.5 on 2023-02-11 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_book_edited_at_alter_contact_edited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingbook',
            name='on_lending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lendingitem',
            name='on_lending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 22, 54, 28, 816334, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 22, 54, 28, 815585, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 22, 54, 28, 817873, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lendingbook',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 22, 54, 28, 817012, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lendingitem',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 22, 54, 28, 818532, tzinfo=datetime.timezone.utc)),
        ),
    ]
